# Generated by Django 5.2.8 on 2025-11-23 01:00

from django.db import migrations


def convert_legacy_agent_nodes(apps, schema_editor):
    """Convert legacy 'agent' type nodes to 'openai_agent' or 'claude_agent'."""
    Workflow = apps.get_model('api', 'Workflow')

    for workflow in Workflow.objects.all():
        nodes = workflow.nodes
        updated = False

        for node in nodes:
            if node.get('type') == 'agent':
                # Check the provider setting in node data
                data = node.get('data', {})
                provider = data.get('provider', 'openai')

                # Convert to specific agent type
                if provider == 'claude':
                    node['type'] = 'claude_agent'
                else:
                    # Default to openai_agent (includes 'openai' and None)
                    node['type'] = 'openai_agent'

                # Remove the provider field as it's no longer needed
                if 'provider' in data:
                    del data['provider']

                updated = True

        if updated:
            workflow.save()


def revert_to_legacy_agent_nodes(apps, schema_editor):
    """Revert openai_agent and claude_agent nodes back to legacy 'agent' type."""
    Workflow = apps.get_model('api', 'Workflow')

    for workflow in Workflow.objects.all():
        nodes = workflow.nodes
        updated = False

        for node in nodes:
            node_type = node.get('type')
            if node_type in ['openai_agent', 'claude_agent']:
                # Set provider based on type
                data = node.get('data', {})
                if node_type == 'claude_agent':
                    data['provider'] = 'claude'
                else:
                    data['provider'] = 'openai'

                # Revert to legacy agent type
                node['type'] = 'agent'
                updated = True

        if updated:
            workflow.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_openai_claude_agent_types'),
    ]

    operations = [
        migrations.RunPython(convert_legacy_agent_nodes, reverse_code=revert_to_legacy_agent_nodes),
    ]
