# Generated by Django 5.2.8 on 2025-11-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_convert_legacy_agent_nodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(default='default', max_length=128)),
                ('key', models.CharField(max_length=256)),
                ('value', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='memoryentry',
            constraint=models.UniqueConstraint(fields=('namespace', 'key'), name='uniq_memory_namespace_key'),
        ),
        migrations.AddIndex(
            model_name='memoryentry',
            index=models.Index(fields=['namespace', 'key'], name='idx_memory_ns_key'),
        ),
    ]

