# Generated by Django 5.2.8 on 2025-11-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_memory_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='api_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='api_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
