# Generated by Django 5.2.8 on 2025-11-23

from django.db import migrations


def add_ollama_agent_type(apps, schema_editor):
    NodeType = apps.get_model('api', 'NodeType')
    item = {
        'name': 'ollama_agent',
        'display_name': 'Ollama Agent',
        'icon': '🟢',
        'color': '#06b6d4',
        'description': 'Local Ollama-powered agent node',
    }
    NodeType.objects.update_or_create(name=item['name'], defaults=item)


def remove_ollama_agent_type(apps, schema_editor):
    NodeType = apps.get_model('api', 'NodeType')
    try:
        NodeType.objects.filter(name='ollama_agent').delete()
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_memory_entry'),
    ]

    operations = [
        migrations.RunPython(add_ollama_agent_type, reverse_code=remove_ollama_agent_type),
    ]

