# Generated by Django 5.2.8 on 2025-11-25 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_workflow_api_enabled_workflow_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('input_data', models.TextField()),
                ('final_output', models.TextField(blank=True)),
                ('status', models.CharField(default='running', max_length=20)),
                ('trace', models.JSONField(default=list)),
                ('error_message', models.TextField(blank=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('triggered_by', models.CharField(default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='api.workflow')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow', '-created_at'], name='api_workflo_workflo_4e8e1c_idx'), models.Index(fields=['execution_id'], name='api_workflo_executi_3916e9_idx')],
            },
        ),
    ]
