# Generated by Django 5.2.8 on 2025-11-24

from django.db import migrations


def add_parallel_join_types(apps, schema_editor):
    NodeType = apps.get_model('api', 'NodeType')
    new_types = [
        {
            'name': 'parallel',
            'display_name': 'Parallel',
            'icon': '⑂',
            'color': '#8b5cf6',
            'description': 'Fork execution into multiple parallel branches',
        },
        {
            'name': 'join',
            'display_name': 'Join',
            'icon': '⑃',
            'color': '#a855f7',
            'description': 'Merge results from parallel branches',
        },
    ]

    for item in new_types:
        NodeType.objects.update_or_create(name=item['name'], defaults=item)


def remove_parallel_join_types(apps, schema_editor):
    NodeType = apps.get_model('api', 'NodeType')
    for name in ['parallel', 'join']:
        try:
            NodeType.objects.filter(name=name).delete()
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_ollama_agent_type'),
    ]

    operations = [
        migrations.RunPython(add_parallel_join_types, reverse_code=remove_parallel_join_types),
    ]
