# Generated by Django 5.2.8 on 2025-11-24 09:06

from django.db import migrations, models


def set_node_categories(apps, schema_editor):
    """Set categories for existing node types."""
    NodeType = apps.get_model('api', 'NodeType')

    # Define category mappings
    categories = {
        'input': 'Input/Output',
        'output': 'Input/Output',
        'openai_agent': 'Agents',
        'claude_agent': 'Agents',
        'ollama_agent': 'Agents',
        'router': 'Control Flow',
        'parallel': 'Control Flow',
        'join': 'Control Flow',
        'memory': 'Data',
        'tool': 'Data',
    }

    # Update each node type
    for name, category in categories.items():
        NodeType.objects.filter(name=name).update(category=category)


def unset_node_categories(apps, schema_editor):
    """Reset categories to default."""
    NodeType = apps.get_model('api', 'NodeType')
    NodeType.objects.all().update(category='Other')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_parallel_join_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nodetype',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='nodetype',
            name='category',
            field=models.CharField(default='Other', max_length=50),
        ),
        migrations.RunPython(set_node_categories, reverse_code=unset_node_categories),
    ]
