# Generated by Django 5.2.8 on 2025-11-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_workflowexecution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowexecution',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='final_output',
            field=models.TextField(blank=True, default=''),
        ),
    ]
