# Generated by Django 5.2.8 on 2025-11-24

from django.db import migrations


def update_node_types(apps, schema_editor):
    """Update condition, action, and trigger node types."""
    NodeType = apps.get_model('api', 'NodeType')

    # Update condition to be in Control Flow category with proper description
    NodeType.objects.filter(name='condition').update(
        category='Control Flow',
        description='Evaluate expressions and route based on true/false result'
    )

    # Mark action and trigger as unimplemented
    NodeType.objects.filter(name='action').update(
        display_name='Action (Unimplemented)',
        description='[NOT IMPLEMENTED] Execute actions based on triggers'
    )

    NodeType.objects.filter(name='trigger').update(
        display_name='Trigger (Unimplemented)',
        description='[NOT IMPLEMENTED] Initiate workflows based on events'
    )


def revert_node_types(apps, schema_editor):
    """Revert node type changes."""
    NodeType = apps.get_model('api', 'NodeType')

    NodeType.objects.filter(name='condition').update(
        category='Other',
        description=''
    )

    NodeType.objects.filter(name='action').update(
        display_name='Action',
        description=''
    )

    NodeType.objects.filter(name='trigger').update(
        display_name='Trigger',
        description=''
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_node_type_category'),
    ]

    operations = [
        migrations.RunPython(update_node_types, reverse_code=revert_node_types),
    ]
