# Generated by Django 5.2.8 on 2025-11-25

from django.db import migrations


def add_json_validator_type(apps, schema_editor):
    NodeType = apps.get_model('api', 'NodeType')
    validator_type = {
        'name': 'json_validator',
        'display_name': 'JSON Validator',
        'icon': '✓',
        'color': '#14b8a6',
        'description': 'Validate JSON data against a schema',
        'category': 'logic',
    }
    NodeType.objects.update_or_create(name=validator_type['name'], defaults=validator_type)


def remove_json_validator_type(apps, schema_editor):
    NodeType = apps.get_model('api', 'NodeType')
    try:
        NodeType.objects.filter(name='json_validator').delete()
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_update_condition_action_trigger'),
    ]

    operations = [
        migrations.RunPython(add_json_validator_type, reverse_code=remove_json_validator_type),
    ]
